### PR TITLE
Makes it testable

### PR DESCRIPTION
**Pull request by magnunleno**
First of all, thanks for this great piece of software.

I've been using it recently and noticed that it isn't testable, I cant fake the recaptcha to be always true in my unit tests. I've made some changes, based on [another lib](https://github.com/praekelt/django-recaptcha/blob/34af16ba1ec8f27d0aeab1ab88d7a35a7b76b1ce/captcha/fields.py#L61) that I used to use, and added some minor documentation.

Thanks in advance!

### CODE REVIEW

**Comment by tech4242** [comment]
@sagar270690 can you please have a look? @magnunleno thank you for your contribution! We will get back to you :)

**Review by sagar270690 — APPROVED** [review]
Looks good. Merging it.  @magnunleno Thanks for your contribution.

**Comment by magnunleno** [comment]
Awesome! Could you guys please push a new version for PyPI? Thanks a lot!

**Comment by DyegoAV** [comment]
Please, push the last version for PyPi! Thanks!

**Comment by sagar270690** [comment]
@magnunleno and @DyegoAV The updated version is pushed to PyPI :+1: Thanks!

**Comment by magnunleno** [comment]
Awesome @sagar270690! Thanks a lot!

**Pull request merged**
